name: 'Login to ghcr.io'
description: 'Log in to the GitHub Container Registry (ghcr.io).'

inputs:
  token:
    description: 'GitHub token to use.'
    required: true

runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
