services:
  php-xd:
    image: ghcr.io/myparcelnl/php-xd:${PHP_XD_PHP_VERSION}-alpine${PHP_XD_ALPINE_VERSION}
    build:
      context: images/php-xd
      args:
        ALPINE_VERSION: ${PHP_XD_ALPINE_VERSION}
        PHP_VERSION: ${PHP_XD_PHP_VERSION}

  wordpress:
    image: ghcr.io/myparcelnl/wordpress:${WP_VERSION}-php${WP_PHP_VERSION}
    build:
      context: images/wordpress
      args:
        WP_VERSION: ${WP_VERSION}
        PHP_VERSION: ${WP_PHP_VERSION}
