services:
  wordpress:
    image: ghcr.io/myparcelnl/wordpress:${WP_VERSION}-php${PHP_VERSION}
    build:
      context: images/wordpress
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        WP_VERSION: ${WP_VERSION}

  prestashop:
    image: ghcr.io/myparcelnl/prestashop:${PS_VERSION}-php${PHP_VERSION}
    build:
      context: images/prestashop
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PS_VERSION: ${PS_VERSION}

  shopware:
    image: ghcr.io/myparcelnl/shopware:${SW_VERSION}-php${PHP_VERSION}
    build:
      context: images/shopware
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        SW_VERSION: ${SW_VERSION}
