services:
  prestashop:
    image: ghcr.io/myparcelnl/prestashop:8.0.5-php8.1
    build:
      context: images/prestashop
      dockerfile: Dockerfile

  shopware:
    image: ghcr.io/myparcelnl/shopware
    build:
      context: images/shopware
      dockerfile: Dockerfile

  wordpress:
    image: ghcr.io/myparcelnl/wordpress:6.3-php7.4
    build:
      context: images/wordpress
      dockerfile: Dockerfile