services:
  elasticsearch:
    image: "myparcel/elasticsearch:${DOCKER_TAG:?6.8.23}"
    build:
      context:   ./
      args:      { ES_VERSION: "${ES_VERSION:?6.8.23}" }
      platforms: [ linux/amd64, linux/arm64 ]
      x-bake:
        platforms: [ linux/amd64, linux/arm64 ]
    environment:
      ES_HEAP_SIZE:          "1024m"
      ES_JAVA_OPTS:          "-Xms1024m -Xmx1024m -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: 'true'
      discovery.type:        "single-node"
      path.repo:  &repo-path "/usr/share/elasticsearch/repo"
    healthcheck:
      test:     ['CMD-SHELL', 'curl -s -f http://localhost:9200/_cluster/health?wait_for_status=green || exit 1']
      interval: 30s
      timeout:  5s
      start_period: 30s
      retries:  3
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
      nproc:   65535
    volumes:
      - { type: volume, source: elasticsearch-data, target: /usr/share/elasticsearch/data }
      - { type: volume, source: elasticsearch-repo, target: *repo-path }
      - { type: bind,   source: ./logs,             target: /usr/share/elasticsearch/logs:cached }

volumes:
  elasticsearch-data:
  elasticsearch-repo:
