name: 'Build and push'
description: 'Builds and pushes an image. Log in to the re'

inputs:
  image:
    description: 'Image suffix'
    required: true

  suffix:
    description: 'Image suffix'
    required: true

  context:
    description: 'Build context'
    required: true

  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'

  build-args:
    description: 'Build arguments'
    required: false
    default: ''

  latest:
    description: 'Whether to push the image with the `latest` tag'
    required: false
    default: 'false'

  cache-mode:
    description: 'Cache mode'
    required: false
    default: 'max'

runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') && inputs.latest == 'true' }} 
          type=raw,value=${{ inputs.suffix }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=branch,suffix=-${{ inputs.suffix }}
          type=ref,event=tag,suffix=-${{ inputs.suffix }}
          type=ref,event=pr,suffix=-${{ inputs.suffix }}

    - uses: docker/build-push-action@v3
      name: build-push
      continue-on-error: true
      with:
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: 'linux/amd64,linux/arm64'
        cache-from: type=gha,scope=build-${{ inputs.suffix }}
        cache-to: type=gha,scope=build-${{ inputs.suffix }},mode=${{ inputs.cache-mode }}

    - name: 'Report'
      if: steps.build-push.outcome == 'success'
      shell: bash
      run: |
        echo "✅ Built ${{ inputs.image }}/${{ inputs.suffix }}" >> $GITHUB_STEP_SUMMARY
