# https://make.wordpress.org/cli/handbook/references/config/
allow-root: true
color: true
path: '${ROOT_DIR}'
url: '${WP_URL_REPLACE}'

config create:
  dbhost: '${DB_HOST}:3306'
  dbname: '${DB_NAME}'
  dbpass: '${DB_PASSWORD}'
  dbprefix: '${DB_PREFIX}'
  dbuser: '${DB_USER}'
  dbcharset: utf8
  extra-php: |
    # Debug
    define('WP_DEBUG', ${WP_DEBUG:-false});
    define('WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY:-false});
    define('WP_DEBUG_LOG', '/tmp/wp-debug.log');
    define('WP_SCRIPT_QUERIES', ${WP_SCRIPT_QUERIES:-false});
    define('SAVEQUERIES', ${SAVEQUERIES:-false});
    define('ALTERNATE_WP_CRON', ${WP_ALTERNATE_WP_CRON:-false});

    @ini_set('display_errors', ${DISPLAY_ERRORS:-0});

    # Force SSL if the URL starts with https://
    if (strpos('${WP_URL_REPLACE}', 'https://') === 0) {
        define('FORCE_SSL_ADMIN', true);
        $$_SERVER['HTTPS'] = 'on';
    }

    # Other
    $$_SERVER['document_root'] = dirname(__FILE__);

core download:
  locale: '${WP_LOCALE:-en_US}'
  version: '${WP_VERSION:-latest}'
  skip-content: true

core install:
  admin_email: '${WP_ADMIN_EMAIL}'
  admin_password: '${WP_ADMIN_PASSWORD}'
  admin_user: '${WP_ADMIN_USER}'
  skip-email: true
  title: '${WP_SITE_NAME:-WordPress}'

user create:
  skip-email: true

rewrite structure:
  hard: true
