name: 'Create version matrix'
description: 'Create a matrix of versions'

inputs:
  versions:
    description: 'Versions as multiline string'
    required: true

  min-version:
    description: 'Minimum version'
    required: false
    default: '0'

  max-version:
    description: 'Maximum version'
    required: false
    default: 'infinite'

outputs:
  matrix:
    description: 'Matrix of versions'
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: 'Create matrix'
      id: matrix
      shell: bash
      #language=bash
      run: |
        MIN_VERSION="${{ inputs.min-version }}"
        MAX_VERSION="${{ inputs.max-version }}"

        JSON=$(echo "${{ inputs.versions }}" | jq -Rsc 'split("\n") | sort | reverse | map(select(. >= "'$MIN_VERSION'" and . <= "'$MAX_VERSION'"))')
        LATEST=$(echo "$JSON" | jq -r '.[0]')
        MATRIX=$(echo "$JSON" | jq -r --arg latest "$LATEST" 'map({version: ., minor: (split(".") | .[0:2] | join(".")), major: (split(".") | .[0]), latest: (. == $latest)})')

        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
