name: 'Build php-xd images'

on:
  push:
    branches:
      - main

    paths:
      - images/php-xd/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  IMAGE: myparcelnl/php-xd
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1']
        alpine: ['3.12', '3.13', '3.14', '3.15', '3.16', '3.17', '3.18', '']
        type: ['-fpm', '-cli', '']
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          context: images/php-xd
          image: myparcelnl/php-xd
          suffix: ${{ matrix.php }}${{ matrix.type }}-alpine${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            PHP_VERSION=${{ matrix.php }}
            TYPE=${{ matrix.type }}

  notify-on-failure:
    needs:
      - build
    if: always() && contains(needs.*.result, 'failure')
    uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v4
    secrets: inherit
