name: 'Build php images'

on:
  push:
    branches:
      - main

    paths:
      - images/php/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: myparcelnl/php-xd
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.2', '7.4', '8.1' ]
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,suffix=-${{ matrix.php }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ matrix.php }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch,suffix=-${{ matrix.php }}
            type=ref,event=tag,suffix=-${{ matrix.php }}
            type=ref,event=pr,suffix=-${{ matrix.php }}
            type=sha,suffix=-${{ matrix.php }}

      - uses: docker/build-push-action@v2
        with:
          context: images/php

          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.php }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
