name: 'Build prestashop images'

on:
  push:
    branches:
      - main

    paths:
      - images/prestashop/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      ps-matrix: ${{ steps.ps.outputs.matrix }}
    steps:
      - name: 'Get all PrestaShop versions as json array'
        id: ps
        #language=bash
        run: |
          # PrestaShop versions without beta, rc, etc.
          result=$(curl -s https://api.github.com/repos/PrestaShop/PrestaShop/tags)
          versions=$(echo "$result" | jq -c '.[].name' | grep -v -E 'beta|rc|alpha|dev' | jq -sc 'unique | reverse')

          echo "matrix=$versions" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1' ]
        ps: ${{ fromJson(needs.prepare.outputs.ps-matrix) }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          cache-mode: 'min'
          context: images/prestashop
          image: myparcelnl/prestashop
          suffix: ${{ matrix.ps }}-php${{ matrix.php }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            PS_VERSION=${{ matrix.ps }}
