name: 'Build wordpress nginx images'

on:
  push:
    branches:
      - main

    paths:
      - images/nginx/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          cache-mode: 'min'
          context: images/wordpress-nginx
          image: myparcelnl/wordpress-nginx
          latest: true
