name: 'Build php-xd images'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.3', '8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1']
        alpine:
          [
            '3.19',
            '3.20',
            '3.22',
            '',
          ]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          context: images/php-xd
          image: myparcelnl/php-xd
          suffix: ${{ matrix.php }}${{ matrix.alpine != '' && format('-alpine{0}', matrix.alpine) || '' }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            PHP_VERSION=${{ matrix.php }}

  notify-on-failure:
    needs:
      - build
    if: always() && contains(needs.*.result, 'failure')
    uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v4
    secrets: inherit
