name: 'Build Elasticsearch images'

on:
  push:
    branches:
      - main

    paths:
      - images/elasticsearch/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: myparcel/elasticsearch
  UBUNTU_DISTRIB_CODENAME: focal

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ES_LATEST_VERSION: '6.8.23'
    strategy:
      fail-fast: false
      matrix:
        es-version:
          - '6.8.23'
          - '6.8.22'
          - '6.8.21'
          - '6.8.20'
    steps:
      - uses: actions/checkout@v3

      # Login to the Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup QEMU for cross-architecture builds
      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: 'Split version into major and minor'
        id: prepare
        run: |
          echo "minor=$(echo ${{ matrix.es-version }} | cut -d. -f1-2)" >> $GITHUB_OUTPUT
          echo "major=$(echo ${{ matrix.es-version }} | cut -d. -f1)" >> $GITHUB_OUTPUT

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            # Tags for main branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && matrix.es-version == env.ES_LATEST_VERSION }}
            type=raw,value=${{ steps.prepare.outputs.major }},enable=${{ github.ref == 'refs/heads/main' && matrix.es-version == env.ES_LATEST_VERSION }}
            type=raw,value=${{ steps.prepare.outputs.minor }},enable=${{ github.ref == 'refs/heads/main' && matrix.es-version == env.ES_LATEST_VERSION }}
            type=raw,value=${{ matrix.es-version }},enable=${{ github.ref == 'refs/heads/main' }}
            
            # Tags for branches, tags and pull requests
            type=ref,event=branch,suffix=-${{ matrix.es-version }}
            type=ref,event=tag,suffix=-${{ matrix.es-version }}
            type=ref,event=pr,suffix=-${{ matrix.es-version }}
            type=sha,suffix=-${{ matrix.es-version }}

      - uses: docker/build-push-action@v3
        continue-on-error: true
        with:
          context: images/elasticsearch
          build-args: |
            ES_VERSION=${{ matrix.es-version }}
            UBUNTU_DISTRIB_CODENAME=${{ env.UBUNTU_DISTRIB_CODENAME }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha,scope=build-${{ matrix.es-version }}
          cache-to: type=gha,scope=build-${{ matrix.es-version }},mode=max
