name: 'Build wordpress images'

on:
  push:
    branches:
      - main

    paths:
      - images/wordpress/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      wp-versions: ${{ steps.wp.outputs.versions }}
      wp-latest: ${{ steps.wp.outputs.latest }}
    steps:
      - name: 'Get all WordPress versions as json array'
        id: wp
        #language=bash
        run: |
          result=$(curl -s https://api.wordpress.org/core/version-check/1.7/)
          versions=$(echo "$result" | jq -rc '[.offers[].version] | unique | reverse')

          echo "versions=$versions"                                 >> $GITHUB_OUTPUT
          echo "latest=$(jq -r '.offers[0].version' <<< "$result")" >> $GITHUB_OUTPUT 

  build:
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        wp: ${{ fromJson(needs.prepare.outputs.wp-versions) }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          context: images/wordpress
          image: myparcelnl/wordpress
          suffix: ${{ matrix.wp }}-php${{ matrix.php }}
          latest: ${{ matrix.wp == needs.prepare.outputs.wp-latest }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            WP_VERSION=${{ matrix.wp }}
