name: 'Build shopware images'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare-php:
    uses: ./.github/workflows/--prepare-php.yml
    secrets: inherit
    with:
      min-version: '8.1'

  build:
    runs-on: ubuntu-22.04
    needs:
      - prepare-php
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']
        sw: ['6.5.0.0']
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/login-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push
        with:
          registry: ghcr.io
          cache-mode: 'min'
          context: images/shopware
          image: myparcelnl/shopware
          suffix: ${{ matrix.sw }}-php${{ matrix.php }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            SW_VERSION=${{ matrix.sw }}

  notify-on-failure:
    needs:
      - build
    if: always() && contains(needs.*.result, 'failure')
    uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v4
    secrets: inherit
