name: 'Build wordpress images'

on:
  push:
    branches:
      - main

    paths:
      - images/wordpress/**/*

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  IMAGE: myparcelnl/wordpress
  REGISTRY: ghcr.io

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      wp-versions: ${{ steps.wp.outputs.versions }}
    steps:
      - name: 'Get all WordPress versions as json array'
        id: wp
        #language=bash
        run: |
          versions=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -rc '[.offers[].version] | unique'

          echo "versions=$versions" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        wp: ${{ fromJson(needs.prepare.outputs.wp-versions) }}
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - id: prepare
        run: |
          echo "identifier=${{ matrix.wp }}-php${{ matrix.php }}" >> $GITHUB_OUTPUT

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,suffix=-${{ steps.prepare.outputs.identifier }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ steps.prepare.outputs.identifier }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch,suffix=-${{ steps.prepare.outputs.identifier }}
            type=ref,event=tag,suffix=-${{ steps.prepare.outputs.identifier }}
            type=ref,event=pr,suffix=-${{ steps.prepare.outputs.identifier }}
            type=sha,suffix=-${{ steps.prepare.outputs.identifier }}

      - uses: docker/build-push-action@v3
        name: build-push
        continue-on-error: true
        with:
          context: images/wordpress
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            WP_VERSION=${{ matrix.wp }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha,scope=build-${{ steps.prepare.outputs.identifier }}
          cache-to: type=gha,scope=build-${{ steps.prepare.outputs.identifier }},mode=max

      - name: 'Report success'
        if: steps.build-push.outcome == 'success'
        shell: bash
        run: |
          echo "- ✅ Built ${{ steps.prepare.outputs.identifier }}"
