name: '⏱️ Schedule workflow run'

on:
  push:
    branches:
      - main

    paths:
      - images/**

  workflow_dispatch:
    inputs:
      image:
        description: 'Image to schedule the workflow for (for testing purposes)'
        required: true
        type: choice
        options:
          - elasticsearch
          - node
          - php-xd
          - prestashop
          - wordpress

jobs:
  schedule:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - elasticsearch
          - node
          - php-xd
          - prestashop
          - shopware
          - wordpress
    steps:
      - uses: actions/checkout@v4

      - uses: tj-actions/changed-files@v46
        id: changed-files
        if: inputs.image == ''
        with:
          files: 'images/${{ matrix.image }}/**'

      - name: 'Prepare'
        if: steps.changed-files.outputs.test_any_changed == 'true' || inputs.image == matrix.image
        id: prepare
        env:
          IMAGE: ${{ matrix.image }}
        shell: bash
        #language=bash
        run: |
          echo "run=true"                           >> $GITHUB_OUTPUT
          echo "filename=.lock-$IMAGE.txt"          >> $GITHUB_OUTPUT
          echo "artifact-name=workflow-lock-$IMAGE" >> $GITHUB_OUTPUT

      - name: 'Check if lock file exists'
        if: steps.prepare.outputs.run == 'true'
        id: find-artifact
        uses: myparcelnl/actions/find-artifact@v4
        with:
          artifact-name: ${{ steps.prepare.outputs.artifact-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.prepare.outputs.run == 'true' && steps.find-artifact.outputs.exists == 'true'
        env:
          IMAGE: ${{ matrix.image }}
        shell: bash
        #language=bash
        run: |
          echo "⏱️ There was already a run scheduled for \`$IMAGE\`." >> $GITHUB_STEP_SUMMARY

      - name: 'Create lock file'
        if: steps.prepare.outputs.run == 'true' && steps.find-artifact.outputs.exists == 'false'
        env:
          FILENAME: ${{ steps.prepare.outputs.filename }}
        shell: bash
        #language=bash
        run: |
          echo "$(date)" > "$FILENAME"

      - name: 'Upload lock artifact'
        uses: actions/upload-artifact@v4
        if: steps.prepare.outputs.run == 'true' && steps.find-artifact.outputs.exists == 'false'
        with:
          if-no-files-found: error
          include-hidden-files: true
          name: ${{ steps.prepare.outputs.artifact-name}}
          path: ${{ steps.prepare.outputs.filename }}

      - name: 'Report'
        if: steps.prepare.outputs.run == 'true' && steps.find-artifact.outputs.exists == 'false'
        env:
          IMAGE: ${{ matrix.image }}
        shell: bash
        #language=bash
        run: |
          echo "✅ A run for \`$IMAGE\` was scheduled." >> $GITHUB_STEP_SUMMARY

  notify-on-failure:
    needs:
      - schedule
    if: always() && contains(needs.*.result, 'failure')
    uses: myparcelnl/actions/.github/workflows/notify-on-failure.yml@v4
    secrets: inherit
